### ISSUE TITLE
[FEAT] fcm 로그인 시 확인, 알림 메세지 수정

### ISSUE THREAD

**Issue by 0sunset0** [meongCare/meongcare-back#108]
## Description
- 앱을 지우고 재설치하면 새 fcm 토큰이 요청오는데 현재 서버에서는 회원가입할 때 db에 저장하기만 해서 수정할 예정입니다.
- fcm 메세지 양식을 수정해달라고 안드로이드 분들이 요청하셔서 수정하겠습니다.
- 알림 메세지 보낼 때 이미지를 전달하고 있는데 안드로이드에서 리소스로 표시하는걸 권장하고 있어서 제거하겠습니다

## ToDo
- [x] fcm 로그인 시 확인하고 다르면 업데이트
- [x] fcm 알림 메세지 수정
- [x] 알림 메세지에 이미지 제외하고 보내기

## ETC
-
