### ISSUE TITLE
[FIX] auth 도메인 버그

### ISSUE THREAD

**Issue by 0sunset0** [meongCare/meongcare-back#94]
## Description
- 

## ToDo
- [x] provider id 구분자 추가해서 저장
- [x] Member 테이블 name 칼럼 삭제, provider id 길이 제한 변경
- [x] validation 에러 잡기, 칼럼 제약 조건 추가
## ETC
-
